# --- 빌드 스테이지 ---
FROM node:18-alpine AS builder

WORKDIR /app

COPY . .

# 환경변수 하드코딩
ENV NEXT_PUBLIC_API_URL=http://localhost:8080

# 개발용: 에러 무시 후 빌드 추후 수정 필요
RUN npm install && npm run build --ignore-build-errors  

# --- 운영 스테이지 ---
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3000

CMD ["npm", "run", "start"]