# --- 빌드 스테이지 ---
FROM node:18-alpine AS builder

WORKDIR /app

COPY . .

# 개발용: 에러 무시 후 빌드
RUN npm install && npm run build --ignore-build-errors  

# 배포용: 타입 검사 포함
# RUN npm install && npm run build


# --- 운영 스테이지 ---
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3000

CMD ["npm", "run", "start"]