# --- 빌드 스테이지 ---
FROM node:18-alpine AS builder

WORKDIR /app

COPY . .

ARG NEXT_PUBLIC_SPRING_API_URL
ENV NEXT_PUBLIC_SPRING_API_URL=${NEXT_PUBLIC_SPRING_API_URL}

RUN npm install && npm run build

# --- 운영 스테이지 ---
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3000

CMD ["npm", "run", "start"]