# 개발용 Dockerfile
FROM node:18-alpine

WORKDIR /app

# package.json, lock만 먼저 복사해서 의존성 캐싱 유도
COPY package*.json ./

# 의존성 설치
RUN npm install

# 전체 프로젝트 복사
COPY . .

# 개발 서버 열기
EXPOSE 3000

# 개발 서버 실행
CMD ["npm", "run", "dev"]