name: Build and Push FastAPI Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: DockerHub 로그인
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: FastAPI Docker 빌드
        run: docker build ./fastapi -f ./fastapi/Dockerfile -t imjjh/fastapi-backend:latest

      - name: 푸시
        run: docker push imjjh/fastapi-backend:latest
