name: Spring Unit Test

on:
  push:
    branches: ["main"]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permission to gradlew
        run: chmod +x backend/gradlew

      - name: Run Unit Tests
        run: ./backend/gradlew test